env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
rules:
  indent:
    - off
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - off
    - single
  semi:
    - error
    - always
  no-console:
    - warn
