DROP TABLE IF EXISTS UserConnection;
DROP TABLE IF EXISTS UserRole;
DROP TABLE IF EXISTS UserSkill;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Skill;
DROP TABLE IF EXISTS Domain;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS Company;
