CREATE TABLE Token (
  id                BIGINT(20) NOT NULL AUTO_INCREMENT,
  token_value       VARCHAR(255) DEFAULT NULL,
  user_id           BIGINT(20) DEFAULT NULL,
  creation_date     DATETIME   DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

ALTER TABLE Token
  ADD CONSTRAINT FK_TOKEN_USER FOREIGN KEY (user_id) REFERENCES User (id);
